"""Vendor/OCR aliases -> canonical laboratory test identifiers.

Aliases are deliberately explicit. A broad substring match is avoided by the
extractor so a phrase such as "SGOT (AST): SGPT (ALT) Ratio" cannot become AST.
"""

ALIASES: dict[str, str] = {
    # CBC core
    "haemoglobin": "hemoglobin",
    "hemoglobin": "hemoglobin",
    "hb": "hemoglobin",
    "hgb": "hemoglobin",
    "packed cell volume": "hematocrit",
    "hematocrit": "hematocrit",
    "pcv": "hematocrit",
    "hct": "hematocrit",
    "total leukocyte count": "wbc",
    "total leucocyte count": "wbc",
    "total wbc count": "wbc",
    "white blood cell count": "wbc",
    "white blood cells": "wbc",
    "wbc count": "wbc",
    "wbc": "wbc",
    "tlc": "wbc",
    "leucocyte count": "wbc",
    "leukocyte count": "wbc",
    "rbc total count": "rbc",
    "red blood cell count": "rbc",
    "rbc count": "rbc",
    "erythrocyte count": "rbc",
    "rbc": "rbc",
    "platelet count": "platelets",
    "platelets count": "platelets",
    "platelets": "platelets",
    "platelet": "platelets",
    "mcv": "mcv",
    "mean corpuscular volume": "mcv",
    "mean corpuscular vol": "mcv",
    "mean corpuscular vol.": "mcv",
    "mch": "mch",
    "mean corpuscular hemoglobin": "mch",
    "mean corpuscular hb.": "mch",
    "mean corpuscular hb": "mch",
    "mchc": "mchc",
    "mean corpuscular hemoglobin concentration": "mchc",
    "mean corpuscular hemoglobin conc": "mchc",
    "mean corpuscular hemoglobin conc.": "mchc",
    "mean corp.hb.con.": "mchc",
    "mean corp.hb.con": "mchc",
    "mean corp hb con": "mchc",
    "mpv": "mpv",
    "mean platelet volume": "mpv",
    "platelet crit": "plateletcrit",
    "plateletcrit": "plateletcrit",
    "pct": "plateletcrit",
    "pdw": "pdw",
    "platelet distribution width": "pdw",
    "p-lcr": "p_lcr",
    "plcr": "p_lcr",
    "platelet large cell ratio": "p_lcr",
    "rdw cv": "rdw",
    "rdw-cv": "rdw",
    "rdw sd": "rdw",
    "rdw-sd": "rdw",
    "rdw": "rdw",
    "red cell distribution width": "rdw",
    "neutrophils": "neutrophils",
    "neutrophil": "neutrophils",
    "neutrophils percent": "neutrophils",
    "lymphocytes": "lymphocytes",
    "lymphocyte": "lymphocytes",
    "lymphocytes percent": "lymphocytes",
    "eosinophils": "eosinophils",
    "eosinophil": "eosinophils",
    "eosinophils percent": "eosinophils",
    "monocytes": "monocytes",
    "monocyte": "monocytes",
    "monocytes percent": "monocytes",
    "basophils": "basophils",
    "basophil": "basophils",
    "basophils percent": "basophils",
    "absolute neutrophil count": "absolute_neutrophil_count",
    "absolute neutrophils count": "absolute_neutrophil_count",
    "anc": "absolute_neutrophil_count",
    "absolute lymphocyte count": "absolute_lymphocyte_count",
    "absolute lymphocytes count": "absolute_lymphocyte_count",
    "alc": "absolute_lymphocyte_count",
    "absolute eosinophil count": "absolute_eosinophil_count",
    "absolute eosinophils count": "absolute_eosinophil_count",
    "aec": "absolute_eosinophil_count",
    "absolute monocyte count": "absolute_monocyte_count",
    "absolute monocytes count": "absolute_monocyte_count",
    "amc": "absolute_monocyte_count",
    "absolute basophils count": "absolute_basophil_count",
    "absolute basophil count": "absolute_basophil_count",
    "abc": "absolute_basophil_count",
    "esr": "esr",
    "sedimentation rate": "esr",
    "erythrocyte sedimentation rate": "esr",

    # Kidney
    "serum creatinine": "creatinine",
    "creatinine": "creatinine",
    "blood urea": "urea",
    "urea": "urea",
    "urea serum": "urea",
    "blood urea nitrogen": "bun",
    "bun": "bun",
    "uric acid": "uric_acid",
    "estimated glomerular filtration rate": "egfr",
    "egfr": "egfr",

    # Electrolytes
    "serum sodium": "sodium",
    "sodium": "sodium",
    "serum potassium": "potassium",
    "potassium": "potassium",
    "serum chloride": "chloride",
    "chloride": "chloride",
    "bicarbonate": "bicarbonate",
    "serum bicarbonate": "bicarbonate",
    "serum calcium": "calcium",
    "calcium": "calcium",

    # Liver
    "total bilirubin": "total_bilirubin",
    "direct bilirubin": "direct_bilirubin",
    "indirect bilirubin": "indirect_bilirubin",
    "sgot / ast": "ast",
    "sgot/ast": "ast",
    "sgot": "ast",
    "ast": "ast",
    "sgpt / alt": "alt",
    "sgpt/alt": "alt",
    "sgpt": "alt",
    "alt": "alt",
    "sgot (ast) : sgpt (alt) ratio": "ast_alt_ratio",
    "sgot (ast) sgpt (alt) ratio": "ast_alt_ratio",
    "ast : alt ratio": "ast_alt_ratio",
    "ast/alt ratio": "ast_alt_ratio",
    "ast alt ratio": "ast_alt_ratio",
    "alkaline phosphatase (alp)": "alp",
    "alkaline phosphatase": "alp",
    "alp": "alp",
    "gamma glutamyl transferase": "ggt",
    "gamma-glutamyl transferase": "ggt",
    "gamma glutamyl transferase (ggt)": "ggt",
    "ggtp": "ggt",
    "ggt": "ggt",
    "total protein": "total_protein",
    "protein-total": "total_protein",
    "protein total": "total_protein",
    "serum albumin": "albumin",
    "albumin": "albumin",
    "globulin": "globulin",
    "a/g ratio": "ag_ratio",
    "albumin globulin ratio": "ag_ratio",

    # Lipid
    "total cholesterol": "total_cholesterol",
    "cholesterol total": "total_cholesterol",
    "serum cholesterol": "total_cholesterol",
    "hdl cholesterol": "hdl",
    "high density lipoprotein": "hdl",
    "hdl - cholesterol": "hdl",
    "hdl": "hdl",
    "ldl cholesterol": "ldl",
    "low density lipoprotein": "ldl",
    "ldl - cholesterol": "ldl",
    "ldl": "ldl",
    "triglycerides": "triglycerides",
    "vldl cholesterol": "vldl",
    "very low density lipoprotein": "vldl",
    "vldl": "vldl",
    "chol / hdl ratio": "chol_hdl_ratio",
    "chol/hdl ratio": "chol_hdl_ratio",
    "chol / hdl ratio.": "chol_hdl_ratio",
    "chol/hdl ratio.": "chol_hdl_ratio",
    "chol / hdl": "chol_hdl_ratio",
    "chol/hdl": "chol_hdl_ratio",
    "hdl/ldl cholesterol ratio": "hdl_ldl_ratio",
    "hdl / ldl cholesterol ratio": "hdl_ldl_ratio",
    "hdl/ldl ratio": "hdl_ldl_ratio",
    "hdl / ldl ratio": "hdl_ldl_ratio",
    "ldl/hdl ratio": "ldl_hdl_ratio",
    "ldl / hdl ratio": "ldl_hdl_ratio",
    "ldl/hdl": "ldl_hdl_ratio",
    "ldl / hdl": "ldl_hdl_ratio",

    # Thyroid
    "thyroid stimulating hormone": "tsh",
    "thyroid stimulating hormone.(tsh)": "tsh",
    "thyroid stimulating hormone (tsh)": "tsh",
    "tsh": "tsh",
    "free t3": "free_t3",
    "ft3": "free_t3",
    "free triiodothyronine": "free_t3",
    "free t4": "free_t4",
    "ft4": "free_t4",
    "free thyroxine": "free_t4",
    "total t3": "total_t3",
    "total triiodothyronine (t3)": "total_t3",
    "total triiodothyronine ( t3 )": "total_t3",
    "total triiodothyronine ( t3)": "total_t3",
    "total triiodothyronine": "total_t3",
    "triiodothyronine": "total_t3",
    "total t4": "total_t4",
    "total thyroxine (t4)": "total_t4",
    "total thyroxine ( t4 )": "total_t4",
    "total thyroxine ( t4)": "total_t4",
    "total thyroxine": "total_t4",
    "thyroxine": "total_t4",

    # Iron
    "total iron binding capacity (tibc)": "tibc",
    "total iron binding capacity": "tibc",
    "tibc": "tibc",
    "transferrin saturation": "transferrin_saturation",
    "transferrin": "transferrin",
    "serum iron": "iron",
    "iron studies": "iron",
    "iron": "iron",
    "ferritin": "ferritin",

    # Diabetes
    "fasting blood sugar (glucose)": "fasting_glucose",
    "fasting blood sugar (fbs)": "fasting_glucose",
    "fasting blood sugar": "fasting_glucose",
    "fasting blood glucose": "fasting_glucose",
    "fasting glucose": "fasting_glucose",
    "random blood glucose": "random_glucose",
    "random blood sugar": "random_glucose",
    "blood glucose": "glucose",
    "glucose": "glucose",
    "hba1c": "hba1c",
    "glycated hemoglobin": "hba1c",
    "glycosylated hemoglobin": "hba1c",
    "glycosylated haemoglobin": "hba1c",
    "glycosylated haemoglobin (hba1c)": "hba1c",
    "glycosylated hemoglobin (hba1c)": "hba1c",
    "approximate mean plasma glucose": "average_glucose",
    "mean plasma glucose": "average_glucose",
    "average blood glucose": "average_glucose",
    "estimated average glucose": "average_glucose",

    # Vitamins / inflammation
    "vitamin d": "vitamin_d",
    "25-oh vitamin ( vit d3 )": "vitamin_d",
    "25-oh vitamin (vit d3)": "vitamin_d",
    "25-oh vitamin": "vitamin_d",
    "vitamin d3": "vitamin_d",
    "vit d3": "vitamin_d",
    "25-hydroxy vitamin d": "vitamin_d",
    "25-oh vitamin d": "vitamin_d",
    "25 oh vitamin d": "vitamin_d",
    "vitamin b12": "vitamin_b12",
    "b12": "vitamin_b12",
    "cyanocobalamin": "vitamin_b12",
    "c-reactive protein": "crp",
    "c - reactive protein": "crp",
    "crp": "crp",

    # Urine Examination
    "colour": "urine_color",
    "color": "urine_color",
    "appearance": "urine_appearance",
    "ph": "urine_ph",
    "specific gravity": "urine_specific_gravity",
    "protein urine": "urine_protein",
    "urine protein": "urine_protein",
    "urobilinogen": "urine_urobilinogen",
    "ketone bodies": "urine_ketone",
    "bile salts": "urine_bile_salts",
    "blood (urine)": "urine_blood",
    "occult blood": "urine_blood",
    "urine blood": "urine_blood",
    "nitrite": "urine_nitrite",
    "glucose urine": "urine_glucose",
    "urine glucose": "urine_glucose",
    "pus cells.": "pus_cells",
    "pus cells": "pus_cells",
    "epithelial cells": "epithelial_cells",
    "rbcs": "urine_rbcs",
    "urine rbcs": "urine_rbcs",
    "casts": "urine_casts",
    "crystals": "urine_crystals",
    "bacteria": "urine_bacteria",
    "others": "urine_others",

    # Endocrine / Hormones
    "dehydroepiandrosterone sulphate (dhea-s)": "dhea_s",
    "dehydroepiandrosterone sulphate": "dhea_s",
    "dehydroepiandrosterone sulfate": "dhea_s",
    "dehydroepiandrosterone": "dhea_s",
    "dehydroepiandrostenedione sulphate (dhea-s)": "dhea_s",
    "dehydroepiandrostenedione sulphate": "dhea_s",
    "dehydroepiandrostenedione sulfate": "dhea_s",
    "dehydroepiandrostenedione": "dhea_s",
    "dhea-s": "dhea_s",
    "dhea s": "dhea_s",
    "dhea": "dhea_s",

    # Microbiology / AST
    "organism isolated": "organism_isolated",
    "organism": "organism_isolated",
    "amikacin": "amikacin",
    "cefepime": "cefepime",
    "ertapenem": "ertapenem",
    "co-trimoxazole": "co_trimoxazole",
    "co trimoxazole": "co_trimoxazole",
    "gentamycin": "gentamycin",
    "gentamicin": "gentamycin",
    "imipenem": "imipenem",
    "meropenem": "meropenem",
    "piperacillin- tazobactum": "piperacillin_tazobactum",
    "piperacillin tazobactum": "piperacillin_tazobactum",
    "piperacillin-tazobactum": "piperacillin_tazobactum",
    "tetracycline": "tetracycline",
    "amoxyclav": "amoxyclav",
    "amoxicillin clavulanate": "amoxyclav",
    "ampicillin": "ampicillin",
    "cefotaxime": "cefotaxime",
    "ceftazidime": "ceftazidime",
    "ceftriaxone": "ceftriaxone",
    "ciprofloxacin": "ciprofloxacin",
    "levofloxacin": "levofloxacin",
    "tobramycin": "tobramycin",

    # Cardiac & Enzymes
    "lactate dehydrogenase (ldh)": "ldh",
    "lactate dehydrogenase": "ldh",
    "serum ldh": "ldh",
    "ldh": "ldh",
    "nt pro b-type natriuric peptide": "nt_probnp",
    "nt pro b type natriuric peptide": "nt_probnp",
    "nt-pro-b-type natriuric peptide": "nt_probnp",
    "nt-probnp": "nt_probnp",
    "nt probnp": "nt_probnp",
    "probnp": "nt_probnp",
    "pro-bnp": "nt_probnp",
    "pro bnp": "nt_probnp",

    # Reproductive & Endocrine
    "sex hormone binding globulin (shbg)": "shbg",
    "sex hormone binding globulin": "shbg",
    "shbg": "shbg",
    "anti mullerian hormone(amh)": "amh",
    "anti mullerian hormone (amh)": "amh",
    "anti mullerian hormone": "amh",
    "anti-mullerian hormone": "amh",
    "amh": "amh",

    # Maternal & Prenatal Screening
    "pregnancy associated plasma protein": "papp_a",
    "pregnancy associated plasma protein a(papp-a)": "papp_a",
    "pregnancy associated plasma protein a (papp-a)": "papp_a",
    "pregnancy associated plasma protein a": "papp_a",
    "pregnancy associated plasma protein-a": "papp_a",
    "papp-a": "papp_a",
    "papp a": "papp_a",
    "mom for papp-a": "papp_a_mom",
    "mom for papp a": "papp_a_mom",
    "papp-a mom": "papp_a_mom",
    "papp a mom": "papp_a_mom",
    "mom papp-a": "papp_a_mom",
    "nt value": "nt_value",
    "nuchal translucency": "nt_value",
    "beta h c g": "beta_hcg",
    "beta hcg": "beta_hcg",
    "beta-hcg": "beta_hcg",
    "b-hcg": "beta_hcg",
    "total beta hcg": "beta_hcg",
    "free beta - hcg": "free_beta_hcg",
    "free beta-hcg": "free_beta_hcg",
    "free beta hcg": "free_beta_hcg",
    "fb-hcg": "free_beta_hcg",
    "fb - hcg": "free_beta_hcg",
    "mom for free beta - hcg": "free_beta_hcg_mom",
    "mom for free beta-hcg": "free_beta_hcg_mom",
    "mom for free beta hcg": "free_beta_hcg_mom",
    "free beta hcg mom": "free_beta_hcg_mom",
    "mom for nuchal translucency": "nt_mom",
    "mom for nt": "nt_mom",
    "nuchal translucency mom": "nt_mom",
    "nt mom": "nt_mom",
    "downs syndrome (t21) biochemical risk": "t21_biochemical_risk",
    "downs syndrome (t21) combined risk": "t21_combined_risk",
    "downs syndrome (t21) maternal age risk": "t21_age_risk",
    "combined trisomy 13/18 with nt risk": "trisomy_13_18_risk",
    "trisomy 13/18 with nt risk": "trisomy_13_18_risk",
    "trisomy 13/18 + nt": "trisomy_13_18_risk",
    "combined trisomy 21 risk": "t21_combined_risk",
    "biochemical t21 risk": "t21_biochemical_risk",
    "age risk": "t21_age_risk",

    # Cytogenetics & Karyotyping
    "karyotype iscn": "karyotype_iscn",
    "iscn karyotype": "karyotype_iscn",
    "karyotype": "karyotype_iscn",
    "karyotype result": "karyotype_result",
    "karyotyping result": "karyotype_result",
    "number of cells analyzed": "cells_analyzed",
    "cells analyzed": "cells_analyzed",
    "number of cells karyotyped": "cells_karyotyped",
    "cells karyotyped": "cells_karyotyped",

    # Liver & Bone
    "bile acid": "bile_acid",
    "bile acids": "bile_acid",
    "total bile acids": "bile_acid",
    "serum bile acid": "bile_acid",
    "serum bile acids": "bile_acid",
    "tba": "bile_acid",
    "alkaline phosphatase with bone fraction ostase": "bone_alkaline_phosphatase",
    "alkaline phosphatase with bone fraction": "bone_alkaline_phosphatase",
    "bone alkaline phosphatase": "bone_alkaline_phosphatase",
    "bone fraction ostase": "bone_alkaline_phosphatase",
    "ostase": "bone_alkaline_phosphatase",

    # Oncology / Tumor Markers
    "ca 15.3": "ca_15_3",
    "ca 15-3": "ca_15_3",
    "ca15.3": "ca_15_3",
    "ca-15-3": "ca_15_3",
    "cancer antigen 15-3": "ca_15_3",

    # Serology & Infectious Disease
    "titre": "titre",
    "titer": "titre",
    "antibody titre": "titre",
    "antibody titer": "titre",
    "herpes simplex virus 1&2 igg": "hsv_1_2_igg",
    "herpes simplex virus 1 and 2 igg": "hsv_1_2_igg",
    "hsv 1&2 igg": "hsv_1_2_igg",
    "hsv 1 and 2 igg": "hsv_1_2_igg",

    # Molecular Diagnostics / COVID RT-PCR
    "rdrp gene": "rdrp_gene",
    "rdrp": "rdrp_gene",
    "s-gene ma": "s_gene_ma",
    "s gene ma": "s_gene_ma",
    "s-gene": "s_gene",
    "s gene": "s_gene",
}
